global.userexist = 'user exist'
global.userregistred = 'user registered successfully..!'
global.somethingwent = 'something went wrong'
global.credentials = 'check details'
global.userlogged = 'user logged successfully'
global.usernot = 'check details'
global.card = 'card status'
global.notfound= 'data not found'
global.noToken ="Token Required"
global.unauthorized ="unauthorized user"
global.usernot = 'user not found'
global.idrequired = "user Id Required"
global.all = "All details Required" 
global.updated = "Data updated successfully"
global.deleted = 'User deleted successfully'